### PR TITLE
 Direct all std::vector assigns through size-aware version 

### LINKED ISSUE #3351: Assign not properly checking bounds on arrays of Eigen objects
The following model raises an eigen assert rather than a proper error:

```stan
parameters {
  array[1] vector[1] theta;
}
transformed parameters {
  array[1] vector[2] wrong_size;
  wrong_size = theta;
}
model {
  theta[1] ~ normal(0, 1);
}
```

If `theta` is moved to data, or if they aren't inside arrays, or if the _array_ sizes mismatch, the correct error gets raised.

I believe the call chain is 
https://github.com/stan-dev/stan/blob/develop/src/stan/model/indexing/assign.hpp#L63
https://github.com/stan-dev/stan/blob/develop/src/stan/model/indexing/access_helpers.hpp#L103

Where the second function does not check if it's values are the same size. I believe that the assign overload should probably disallow vectors the same way it disallows tuples, or at least disallow them if the vectors contain anything other than scalars?

### PR DESCRIPTION
**Pull request by WardBrian**
#### Submission Checklist

- [x] Run unit tests: `./runTests.py src/test/unit`
- [x] Run cpplint: `make cpplint`
- [x] Declare copyright holder and open-source license: see below

#### Summary

Closes #3351 

#### Intended Effect

More size mismatch errors are properly caught by Stan

#### How to Verify

New test added, which crashes on `develop` and passes on this branch.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

Simons Foundation

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

File: src/stan/model/indexing/assign.hpp [hunk 1]
```diff
@@ -776,15 +777,24 @@ inline void assign(Mat1&& x, Mat2&& y, const char* name, const Idx& row_idx,
...
+    if (is_stan_scalar_v<value_type_t<T>> || x.size() == 0) {
+      x = std::forward<U>(y);
+      return;
+    }
+  }
+
+  // If we've made it this far, we need x to have elements to assign to,
+  // and we know this is either a no-op or x has size 0
+  x.resize(y.size());
+  if constexpr (std::is_rvalue_reference_v<U&&>) {
```
Comment (SteveBronder) [inline src/stan/model/indexing/assign.hpp]: If we are trying to fix the case of the below does this do what we intend?

```
parameters {
  array[1] vector[1] theta;
}
transformed parameters {
  array[1] vector[2] wrong_size;
  wrong_size = theta;
}
```

idt we want to resize `wrong_size` here. Shouldn't this throw an error?

Comment (WardBrian) [reply src/stan/model/indexing/assign.hpp]: The first part of this function checks the sizes match if x is not size 0, and will throw an exception. 

So, when this line executes it is guaranteed that x.size == y.size OR x.size == 0. If the sizes match, this resize does nothing. 

But if x was size 0, and we can’t just directly assign to it, we need to resize it or else x[i] will blow up in the following loop

Comment (WardBrian) [reply src/stan/model/indexing/assign.hpp]: In particular, this is the test I added, and the test still asserts that this throws an error, it just no longer _crashes_.

**Review by SteveBronder — APPROVED** [review]
