### PR TITLE
Only swallow domain_errors in various algorithms 

### LINKED ISSUE #3258: Remove places where exceptions are unconditionally swallowed.
#### Summary:

There are a few places where we catch `std::exception` and do not end up re-throwing it. This prevents features like https://github.com/stan-dev/stanc3/issues/1393 (an `exit()` function in the language), and leads to some unexpected behavior.

For example, if an indexing exception occurs during initialization, the program halts. If it occurs during _sampling_, it's all good. Run this program a few times to get a sense of this:

```stan
parameters {
  real mu;
}
model {
  mu ~ normal(0, 1);
  
  if (mu < 0) {
    array[1] int sigma;
    print(sigma[2]);
  }
}
```

#### Description:

I believe I have found the relevant places that need to change and highlighted them here: https://gist.github.com/WardBrian/a21b6e650606e562ca1466eedaa3eb47

When a similar change was made in https://github.com/stan-dev/stan/pull/2307, the choice was to not catch anything that isn't a `std::domain_error`. This is what `reject()` throws in the language, and a lot of our math functions as well, and generally seems like a good choice for "recoverable".

#### Current Version:
v2.34

### PR DESCRIPTION
**Pull request by WardBrian**
#### Submission Checklist

- [x] Run unit tests: `./runTests.py src/test/unit`
- [x] Run cpplint: `make cpplint`
- [x] Declare copyright holder and open-source license: see below

#### Summary

Closes #3258. This changes any place which caught `std::exception` from the model to only catch `std::domain_error`, matching what is done during initialization. 

This prevents odd behavior like an indexing exception that only occurs randomly being swallowed if initialization happens to pass, and allows things like an `exit()` function in the language.

#### Intended Effect

Cause certain exceptions to terminate the inference algorithms.

#### How to Verify

This model will usually initialize but quickly fail now: 

```stan
parameters {
  real mu;
}
model {
  mu ~ normal(0, 1);

  if (mu > 1) {
    array[1] int sigma;
    print(sigma[2]);
  }
}
```

#### Side Effects

I've installed handlers in the service functions, but code that calls the internals of these algorithms (e.g `run_adaptive_sampler`) _not_ through the services will need to be ready to catch exceptions

Additionally, if any Math functions raise an exception which is intended to be recoverable but is not a domain_error, they will need updating. Because this is the current behavior in initialization, I suspect we have probably already smoked any of these out.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

Simons Foundation

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by WardBrian** [comment]
This is failing downstream due to https://github.com/stan-dev/math/issues/1039: Some CVODES errors are still thrown as generic `runtime_error`s in https://github.com/stan-dev/math/blob/develop/stan/math/prim/err/check_flag_sundials.hpp

@syclik - the discussion from back then suggested these becoming `domain_error`s, but they didn't. Was there some reason for this, or should I go ahead and open a PR to math which does that?

File: src/stan/services/optimize/bfgs.hpp [hunk 1]
```diff
@@ -119,7 +128,13 @@ int bfgs(Model& model, const stan::io::var_context& init,
           "  # evals"
           "  Notes ");
 
-    ret = bfgs.step();
+    try {
+      ret = bfgs.step();
+    } catch (const std::exception& e) {
+      logger.error(e.what());
+      return error_codes::SOFTWARE;
+    }
```
Comment (SteveBronder) [inline src/stan/services/optimize/bfgs.hpp:136]: Can we move this to the outer part of the while loop?

File: src/stan/services/optimize/lbfgs.hpp [hunk 2]
```diff
@@ -123,7 +123,12 @@ int lbfgs(Model& model, const stan::io::var_context& init,
           "  # evals"
           "  Notes ");
 
-    ret = lbfgs.step();
+    try {
+      ret = lbfgs.step();
+    } catch (const std::exception& e) {
+      logger.error(e.what());
+      return error_codes::SOFTWARE;
+    }
```
Comment (SteveBronder) [inline src/stan/services/optimize/lbfgs.hpp:131]: Same here. Generally for any while loops I'd like to just have the try on the outside

File: src/stan/services/pathfinder/multi.hpp [hunk 3]
```diff
@@ -117,28 +117,33 @@ inline int pathfinder_lbfgs_multi(
...
+                    model, *(init[iter]), random_seed, stride_id + iter,
+                    init_radius, history_size, init_alpha, tol_obj, tol_rel_obj,
+                    tol_grad, tol_rel_grad, tol_param, num_iterations,
+                    num_elbo_draws, num_draws, save_iterations, refresh,
+                    interrupt, logger, init_writers[iter],
+                    single_path_parameter_writer[iter],
+                    single_path_diagnostic_writer[iter], calculate_lp);
+            if (unlikely(std::get<0>(pathfinder_ret) != error_codes::OK)) {
+              logger.error(std::string("Pathfinder iteration: ")
+                           + std::to_string(iter) + " failed.");
```
Comment (SteveBronder) [inline src/stan/services/pathfinder/multi.hpp:135]: If we are already throwing in the individual pathfinder do we need this message?

File: src/stan/services/pathfinder/single.hpp [hunk 4]
```diff
@@ -820,7 +820,16 @@ inline auto pathfinder_lbfgs_single(
         logger.info(lbfgs_ss);
         lbfgs_ss.str("");
       }
-      throw e;
+      if (ReturnLpSamples) {
+        // we want to terminate multi-path pathfinder during these unrecoverable
+        // exceptions
+        throw;
```
Comment (SteveBronder) [inline src/stan/services/pathfinder/single.hpp:826]: Why? One pathfinder can fail while the others succeed?

File: src/stan/services/pathfinder/single.hpp [hunk 5]
```diff
@@ -820,7 +820,16 @@ inline auto pathfinder_lbfgs_single(
...
+      } else {
+        logger.error(e.what());
```
Comment (SteveBronder) [inline src/stan/services/pathfinder/single.hpp:828]: `path_num` should be appended to this message?

**Review by SteveBronder — APPROVED** [review]
I think this is fine, one thing I would like clarified is what happens to things like `std::out_of_range` errors.

File: src/stan/services/optimize/lbfgs.hpp (hunk 2 above)
Comment (WardBrian) [reply src/stan/services/optimize/lbfgs.hpp:131]: Moved both

File: src/stan/services/pathfinder/single.hpp (hunk 5 above)
Comment (WardBrian) [reply src/stan/services/pathfinder/single.hpp:828]: If `ReturnLPSamples` is false, we're always in single path pathfinder, right? If so, I don't think the path number is important

File: src/stan/services/pathfinder/multi.hpp (hunk 3 above)
Comment (WardBrian) [reply src/stan/services/pathfinder/multi.hpp:135]: This can still happen if e.g. a path fails to initialize. That isn't fatal to the entire algorithm, so it will trigger this message, which I think is still valuable.

**Comment by WardBrian** [comment]
`std::out_of_range` would be considered fatal by this and lead to the algorithms terminating. Is there something else you're looking for clarification on about them?

File: src/stan/services/pathfinder/single.hpp (hunk 5 above)
Comment (SteveBronder) [reply src/stan/services/pathfinder/single.hpp:828]: Whoops! Wrong order that is correct

File: src/stan/services/pathfinder/single.hpp (hunk 4 above)
Comment (SteveBronder) [reply src/stan/services/pathfinder/single.hpp:826]: > If one path does something unrecoverable like indexes into a vector out of bounds, I think the right thing to do is stop and say "something is clearly wrong with your model".

Are only unrecoverable errors able to be thrown here? Like if the call to log_prob throws it could be from something recoverable like one of the ode solvers failing for a given set of parameters

Comment (WardBrian) [reply src/stan/services/pathfinder/single.hpp:826]: `pathfinder_impl` catches `std::domain_error`s, which is what the ODE solvers throw (and is generally what the math library considers 'recoverable')

**Comment by WardBrian** [comment]
Those have been considered unrecoverable (at least during initialization) for a while. `invalid_argument` is thrown for things like `check_square`, which won't change if you just 'try again'.

I think if there are usages in Math we want to be recoverable, we should change those to match the others

**Comment by SteveBronder** [comment]
Okay looking at this again I think this is fine to merge 👍
